import { Type } from '@sinclair/typebox';
import HourDataSchema from './hour-data-schema';

const DayDataSchema = Type.Object({
  datetime: Type.String(),
  datetimeEpoch: Type.Number(),
  tempmax: Type.Number(),
  tempmin: Type.Number(),
  temp: Type.Number(),
  feelslikemax: Type.Number(),
  feelslikemin: Type.Number(),
  feelslike: Type.Number(),
  dew: Type.Number(),
  humidity: Type.Number(),
  precip: Type.Number(),
  precipprob: Type.Number(),
  precipcover: Type.Number(),
  preciptype: Type.Optional(Type.Array(Type.String())),
  snow: Type.Number(),
  snowdepth: Type.Number(),
  windgust: Type.Number(),
  windspeed: Type.Number(),
  winddir: Type.Number(),
  pressure: Type.Number(),
  cloudcover: Type.Number(),
  visibility: Type.Number(),
  solarradiation: Type.Number(),
  solarenergy: Type.Number(),
  uvindex: Type.Number(),
  severerisk: Type.Number(),
  sunrise: Type.String(),
  sunriseEpoch: Type.Number(),
  sunset: Type.String(),
  sunsetEpoch: Type.Number(),
  moonphase: Type.Number(),
  conditions: Type.String(),
  description: Type.String(),
  icon: Type.String(),
  stations: Type.Optional(Type.Array(Type.String())),
  source: Type.String(),
  hours: Type.Array(HourDataSchema),
});

export default DayDataSchema;
